# Generated by Django 4.0 on 2021-12-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('time_pup', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='kashi/')),
            ],
        ),
    ]
