# Generated by Django 4.0 on 2021-12-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kash',
            name='discription',
            field=models.CharField(max_length=50, verbose_name='نوضیحات'),
        ),
        migrations.AlterField(
            model_name='kash',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='kash',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='kash',
            name='time_pup',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
