# Generated by Django 4.0 on 2021-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashi', '0002_alter_kash_discription_alter_kash_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kash',
            name='type_kash',
            field=models.CharField(choices=[('b', 'بزرگ'), ('k', 'کوچک'), ('m', 'متوسط')], default='m', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
